# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\x8a\x01\n\x10\x43\x61lculateRequest\x12\x1b\n\x0e\x63\x61lculate_type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\x1c\n\x10input_num_values\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x12\n\ninput_nums\x18\x05 \x03(\x05\x42\x11\n\x0f_calculate_type\" \n\x0e\x43\x61lculateReply\x12\x0e\n\x06result\x18\x01 \x01(\t2\xb0\x02\n\tCalculate\x12\x45\n\x07GetPlus\x12\x1c.calculator.CalculateRequest\x1a\x1a.calculator.CalculateReply\"\x00\x12\x46\n\x08GetMinus\x12\x1c.calculator.CalculateRequest\x1a\x1a.calculator.CalculateReply\"\x00\x12I\n\x0bGetMultiply\x12\x1c.calculator.CalculateRequest\x1a\x1a.calculator.CalculateReply\"\x00\x12I\n\x0bGetDivision\x12\x1c.calculator.CalculateRequest\x1a\x1a.calculator.CalculateReply\"\x00\x62\x06proto3'
)




_CALCULATEREQUEST = _descriptor.Descriptor(
  name='CalculateRequest',
  full_name='calculator.CalculateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calculate_type', full_name='calculator.CalculateRequest.calculate_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='calculator.CalculateRequest.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='calculator.CalculateRequest.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_num_values', full_name='calculator.CalculateRequest.input_num_values', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_nums', full_name='calculator.CalculateRequest.input_nums', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_calculate_type', full_name='calculator.CalculateRequest._calculate_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=33,
  serialized_end=171,
)


_CALCULATEREPLY = _descriptor.Descriptor(
  name='CalculateReply',
  full_name='calculator.CalculateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.CalculateReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=205,
)

_CALCULATEREQUEST.oneofs_by_name['_calculate_type'].fields.append(
  _CALCULATEREQUEST.fields_by_name['calculate_type'])
_CALCULATEREQUEST.fields_by_name['calculate_type'].containing_oneof = _CALCULATEREQUEST.oneofs_by_name['_calculate_type']
DESCRIPTOR.message_types_by_name['CalculateRequest'] = _CALCULATEREQUEST
DESCRIPTOR.message_types_by_name['CalculateReply'] = _CALCULATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateRequest = _reflection.GeneratedProtocolMessageType('CalculateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculateRequest)
  })
_sym_db.RegisterMessage(CalculateRequest)

CalculateReply = _reflection.GeneratedProtocolMessageType('CalculateReply', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEREPLY,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculateReply)
  })
_sym_db.RegisterMessage(CalculateReply)


_CALCULATEREQUEST.fields_by_name['input_num_values']._options = None

_CALCULATE = _descriptor.ServiceDescriptor(
  name='Calculate',
  full_name='calculator.Calculate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=512,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPlus',
    full_name='calculator.Calculate.GetPlus',
    index=0,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMinus',
    full_name='calculator.Calculate.GetMinus',
    index=1,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMultiply',
    full_name='calculator.Calculate.GetMultiply',
    index=2,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDivision',
    full_name='calculator.Calculate.GetDivision',
    index=3,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATE)

DESCRIPTOR.services_by_name['Calculate'] = _CALCULATE

# @@protoc_insertion_point(module_scope)
