# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CalculateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlus = channel.unary_unary(
                '/calculator.Calculate/GetPlus',
                request_serializer=calculator__pb2.CalculateRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculateReply.FromString,
                )
        self.GetMinus = channel.unary_unary(
                '/calculator.Calculate/GetMinus',
                request_serializer=calculator__pb2.CalculateRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculateReply.FromString,
                )
        self.GetMultiply = channel.unary_unary(
                '/calculator.Calculate/GetMultiply',
                request_serializer=calculator__pb2.CalculateRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculateReply.FromString,
                )
        self.GetDivision = channel.unary_unary(
                '/calculator.Calculate/GetDivision',
                request_serializer=calculator__pb2.CalculateRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculateReply.FromString,
                )


class CalculateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMinus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMultiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDivision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlus,
                    request_deserializer=calculator__pb2.CalculateRequest.FromString,
                    response_serializer=calculator__pb2.CalculateReply.SerializeToString,
            ),
            'GetMinus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinus,
                    request_deserializer=calculator__pb2.CalculateRequest.FromString,
                    response_serializer=calculator__pb2.CalculateReply.SerializeToString,
            ),
            'GetMultiply': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultiply,
                    request_deserializer=calculator__pb2.CalculateRequest.FromString,
                    response_serializer=calculator__pb2.CalculateReply.SerializeToString,
            ),
            'GetDivision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDivision,
                    request_deserializer=calculator__pb2.CalculateRequest.FromString,
                    response_serializer=calculator__pb2.CalculateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculate/GetPlus',
            calculator__pb2.CalculateRequest.SerializeToString,
            calculator__pb2.CalculateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMinus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculate/GetMinus',
            calculator__pb2.CalculateRequest.SerializeToString,
            calculator__pb2.CalculateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMultiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculate/GetMultiply',
            calculator__pb2.CalculateRequest.SerializeToString,
            calculator__pb2.CalculateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDivision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculate/GetDivision',
            calculator__pb2.CalculateRequest.SerializeToString,
            calculator__pb2.CalculateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
